# AI Note System Development Configuration

# API Keys
OPENAI_API_KEY: "your_key_here"
NOTION_TOKEN: "your_token_here"

# Notion Integration
DATABASE_ID: "your_notion_db_id"

# Input Settings
PDF_EXTRACTION_METHOD: "PyMuPDF"  # Options: PyMuPDF, pdf2image+OCR
OCR_ENGINE: "pytesseract"  # Options: pytesseract, EasyOCR
SPEECH_RECOGNITION_ENGINE: "whisper"  # Options: whisper, SpeechRecognition

# Processing Settings
LLM_MODEL: "gpt-3.5-turbo"  # Using cheaper model for development
EMBEDDING_MODEL: "text-embedding-ada-002"
SUMMARIZATION_MAX_LENGTH: 500
KEYPOINTS_MAX_COUNT: 10
ACTIVE_RECALL_QUESTIONS_COUNT: 5

# Visualization Settings
FLOWCHART_ENGINE: "mermaid"
MINDMAP_ENGINE: "mermaid"
TIMELINE_ENGINE: "mermaid"
TREEGRAPH_ENGINE: "graphviz"

# Output Settings
DEFAULT_EXPORT_FORMAT: "markdown"
NOTION_AUTO_SYNC: false  # Disabled in development
SPACED_REPETITION_ALGORITHM: "SM-2"

# Database Settings
DATABASE_TYPE: "sqlite"
DATABASE_PATH: "../data/pansophy_dev.db"  # Development-specific database

# Logging Settings
LOG_LEVEL: "DEBUG"  # More verbose logging in development
LOG_FILE: "../logs/ai_note_system_dev.log"

# Advanced Settings
CACHE_EMBEDDINGS: true
AUTO_LINKING_THRESHOLD: 0.75
MISCONCEPTION_CHECK_ENABLED: true
SIMPLIFICATION_ENABLED: true

# Development-specific settings
DEVELOPMENT_MODE: true
MOCK_API_CALLS: false  # Set to true to use mock API responses
RELOAD_ON_CHANGE: true  # Auto-reload when code changes
PROFILE_PERFORMANCE: true  # Enable performance profiling