# AI Note System Production Configuration

# API Keys
OPENAI_API_KEY: "your_key_here"
NOTION_TOKEN: "your_token_here"

# Notion Integration
DATABASE_ID: "your_notion_db_id"

# Input Settings
PDF_EXTRACTION_METHOD: "PyMuPDF"  # More reliable method for production
OCR_ENGINE: "pytesseract"
SPEECH_RECOGNITION_ENGINE: "whisper"  # More accurate for production

# Processing Settings
LLM_MODEL: "gpt-4"  # Using best model for production
EMBEDDING_MODEL: "text-embedding-ada-002"
SUMMARIZATION_MAX_LENGTH: 500
KEYPOINTS_MAX_COUNT: 10
ACTIVE_RECALL_QUESTIONS_COUNT: 5

# Visualization Settings
FLOWCHART_ENGINE: "mermaid"
MINDMAP_ENGINE: "mermaid"
TIMELINE_ENGINE: "mermaid"
TREEGRAPH_ENGINE: "graphviz"

# Output Settings
DEFAULT_EXPORT_FORMAT: "markdown"
NOTION_AUTO_SYNC: true  # Enabled in production
SPACED_REPETITION_ALGORITHM: "SM-2"

# Database Settings
DATABASE_TYPE: "sqlite"
DATABASE_PATH: "../data/pansophy.db"

# Logging Settings
LOG_LEVEL: "WARNING"  # Less verbose logging in production
LOG_FILE: "../logs/ai_note_system.log"

# Advanced Settings
CACHE_EMBEDDINGS: true
AUTO_LINKING_THRESHOLD: 0.75
MISCONCEPTION_CHECK_ENABLED: true
SIMPLIFICATION_ENABLED: true

# Production-specific settings
PRODUCTION_MODE: true
ENABLE_CACHING: true  # Enable caching for better performance
RATE_LIMITING: true  # Enable rate limiting for API calls
MAX_CONCURRENT_REQUESTS: 5  # Limit concurrent requests
TIMEOUT_SECONDS: 30  # Set timeout for external API calls
ERROR_REPORTING: true  # Enable detailed error reporting
BACKUP_ENABLED: true  # Enable automatic backups
BACKUP_INTERVAL_HOURS: 24  # Backup every 24 hours