apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-note-system.fullname" . }}
  labels:
    {{- include "ai-note-system.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ai-note-system.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ai-note-system.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ai-note-system.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          env:
            - name: ORACLE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "ai-note-system.fullname" . }}-secret
                  key: oracleConnectionString
            - name: ORACLE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "ai-note-system.fullname" . }}-secret
                  key: oracleUsername
            - name: ORACLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ai-note-system.fullname" . }}-secret
                  key: oraclePassword
            - name: ORACLE_WALLET_LOCATION
              value: {{ .Values.env.oracleWalletLocation }}
            - name: LOG_LEVEL
              value: {{ .Values.env.logLevel }}
            - name: PORT
              value: {{ .Values.env.port | quote }}
            - name: MODEL_PATH
              value: {{ .Values.env.modelPath }}
            - name: MODEL_VERSION
              value: {{ .Values.env.modelVersion }}
            - name: OBJECT_STORAGE_BUCKET
              value: {{ .Values.env.objectStorageBucket }}
            - name: OBJECT_STORAGE_NAMESPACE
              value: {{ .Values.env.objectStorageNamespace }}
            - name: EMAIL_ENABLED
              value: {{ .Values.env.emailEnabled | quote }}
            - name: EMAIL_SENDER
              value: {{ .Values.env.emailSender }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: models-volume
              mountPath: {{ .Values.persistence.models.mountPath }}
            - name: wallet-volume
              mountPath: {{ .Values.persistence.wallet.mountPath }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: models-volume
          persistentVolumeClaim:
            claimName: {{ include "ai-note-system.fullname" . }}-models
        - name: wallet-volume
          persistentVolumeClaim:
            claimName: {{ include "ai-note-system.fullname" . }}-wallet
        {{- end }}